FROM continuumio/miniconda3:latest
MAINTAINER Oscar Araque

RUN mkdir /app
WORKDIR /app

RUN conda install -c https://conda.anaconda.org/sloria textblob 
RUN python -m textblob.download_corpora lite

COPY . /app

VOLUME /input.txt
VOLUME /output.txt

CMD python run.py /input.txt /output.txt
